### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by halbielee** [lsa1997/CARIS#2]
Thank you for sharing excellent work!

I am wondering which version the code uses.

Thank you!

**Comment by lsa1997** [comment]
Hi, our code is verified with Python 3.8 and PyTorch 1.11. Other dependencies are listed in [requirements.txt](https://github.com/lsa1997/CARIS/blob/main/requirements.txt).

**Comment by halbielee** [comment]
Thank you for your kind reply!

**Comment by halbielee** [comment]
Thank you for your kind reply!
