### ISSUE TITLE
RefCOCOm dataset

### ISSUE THREAD

**Issue by PanXiongAdam** [lsa1997/CARIS#3]
Hello, Sir!
This is an interesting work, can you open the ref-cocom dataset?

Thank you.
Sincerely.

**Comment by lsa1997** [comment]
Hi, please check [here](https://github.com/lsa1997/CARIS?tab=readme-ov-file#datasets) to download refcocom.

**Comment by PanXiongAdam** [comment]
> Hi, please check [here](https://github.com/lsa1997/CARIS?tab=readme-ov-file#datasets) to download refcocom.

@lsa1997 Thank you for your reply, but you provide the combined annotations as refcocom (https://drive.google.com/file/d/1_WnCziCIVHXpWYDsIsHbxzH_KCiYhflo/view?usp=sharing). 
We need access permissions to enter the display and have been unable to access the data.
![Snipaste_2024-01-23_14-47-23](https://github.com/lsa1997/CARIS/assets/32896464/07cc77ca-93af-44f2-aeac-57c44a7edbd1)

**Comment by lsa1997** [comment]
Sorry for the inconvenience. I have updated the permission, please try again.

**Comment by PanXiongAdam** [comment]
> Sorry for the inconvenience. I have updated the permission, please try again.

Thank you.

**Comment by PanXiongAdam** [comment]
@lsa1997 Sorry to bother you again. What data is used to test the model when we train the model? Because the model is trained and tested when epoch % 10 == 0 or epoch >= args.epochs - 16

**Comment by lsa1997** [comment]
You can use the script for refcoco [here](https://github.com/lsa1997/CARIS/blob/main/scripts/train_refcoco.sh) and add `--mix` to use refcocom for training. Keep `DATASET=refcoco` to use refcoco val for cross validation during training. I will update README later to clarify this.
After training, you can evaluate the trained model on each dataset.

**Comment by PanXiongAdam** [comment]
> You can use the script for refcoco [here](https://github.com/lsa1997/CARIS/blob/main/scripts/train_refcoco.sh) and add `--mix` to use refcocom for training. Keep `DATASET=refcoco` to use refcoco val for cross validation during training. I will update README later to clarify this. After training, you can evaluate the trained model on each dataset.

Thank you very much. I complete and run it.
