### ISSUE TITLE
Is it OK to use it for our RIS paper?

### ISSUE THREAD

**Issue by bhheo** [lsa1997/CARIS#6]
Hi,

Thank you for sharing this repo.
My team conducted RIS research using your code, and it has been very helpful.

We are preparing to upload our paper to arXiv and release our code that is built upon yours.
But, since there is no license in this repository, our license manager asked us to get your permission.

Would it be okay to use this code for our RIS paper and release code based on it?
We will cite your paper and include a link to this repository to show your contribution.

Thank you for your help!

Best regards,
Heo

**Comment by lsa1997** [comment]
Hi, we’ve added the MIT license to the repository, and you’re welcome to use the code for your paper.

**Comment by bhheo** [comment]
Thank you!
That is a perfect solution to my issue.
